_user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("dashboard/", views.dashboard_view, name="dashboard"),
    # ****************************************************************
    # * Transfer views
    # ****************************************************************
    path("transfer/local/", views.interbank_transfer_view, name="interbank_transfer"),
    path("transfer/wire/", views.wire_transfer_view, name="wire_transfer"),
    path(
        "transfer/wire/recipient/add/",
        views.add_a_wire_transfer_recipient_view,
        name="add_a_wire_transfer_recipient",
    ),
    path(
        "transfer/wire/history/",
        views.wire_transfer_history_view,
        name="wire_transfer_history",
    ),
    path(
        "transfer/deposit-check/",
        views.deposit_check_view,
        name="deposit_check",
    ),
    path(
        "transfer/",
        views.other_bank_transfer_view,
        name="other_bank_transfer",
    ),
    # ****************************************************************
    # * Pay a biller views
    # ****************************************************************
    path("pay-bills/", views.pay_a_biller_view, name="pay_a_biller"),
    path("pay-bills/add-payee/", views.add_a_payee_view, name="add_a_payee"),
    path(
        "pay-bills/history/",
        views.pay_a_biller_history_view,
        name="pay_a_biller_history",
    ),
    # ****************************************************************
    # * virtual card views
    # ****************************************************************
    path("virtual-card/", views.virtual_card_view, name="virtual_card"),
    path(
        "virtual-card/application/",
        views.virtual_card_application_view,
        name="virtual_card_application",
    ),
    # ****************************************************************
    # * Loan views
    # ****************************************************************
    path("loans/request/", views.new_loan_request_view, name="new_loan_request"),
    path(
        "loans/history/",
        views.loan_history_view,
        name="loan_history",
    ),
    path("summary/", views.transaction_history_view, name="transaction_history"),
    path("account-settings/", views.account_settings_view, name="account_settings"),
    path("kyc/", views.kyc_verification_view, name="kyc_verification"),
    path("kyc-form/", views.complete_verification_view, name="complete_verification"),
    path("contact/", views.support_ticket_view, name="support_ticket"),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [path("", views.home_view, name="home")]

banking/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("app.urls", namespace="public")),
    path("admin/", include("_admin.urls", namespace="admin")),
    path("personal-banking/", include("_user.urls", namespace="user")),
    path("auth/secure/", include("accounts.urls", namespace="auth")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/user/transfer/wire/add-a-recipient.html
{% extends '../../_base.html' %}
{% load static %}

{% block title %}
Add wire transfer recipient
{% endblock %}

{% block content %}
<div class="space-y-10">
    {% include './top-banner.html' %}

    <div class="flex flex-col">
        {% include './tab-menu.html' %}

        <div class="p-8 border border-gray-800 space-y-5 bg-[#141C26] shadow-mg shadow-black">
            <h3 class="font-semibold text-gray-600 text-md">Recipient's and banking information</h3>

            <form class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5" method="post">
                {% csrf_token %}

                <div class="space-y-2">
                    <label for="country" class="font-medium text-white text-md">Country</label>
                    <select name="country" id="country"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full">
                        <option value="------">Select Country</option>
                    </select>
                </div>
                <div class="space-y-2">
                    <label for="state" class="font-medium text-white text-md">State</label>
                    <select name="state" id="state"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full">
                        <option value="------">Select State</option>
                    </select>
                </div>
                <div class="space-y-2">
                    <label for="city" class="font-medium text-white text-md">City</label>
                    <input type="text" name="city" id="city"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                        placeholder="City" />
                </div>
                <div class="space-y-2 col-span-3">
                    <label for="address" class="font-medium text-white text-md">Address</label>
                    <input type="text" name="address" id="address"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                        placeholder="Address" />
                </div>
                <div class="space-y-2">
                    <label for="postal" class="font-medium text-white text-md">Postal/Zipcode</label>
                    <input type="text" name="postal" id="postal"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                        placeholder="Postal/Zipcode" />
                </div>
                <div class="space-y-2">
                    <label for="email" class="font-medium text-white text-md">Email Address</label>
                    <input type="email" name="email" id="email"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                        placeholder="Email Address" />
                </div>
                <div class="space-y-2">
                    <label for="phone" class="font-medium text-white text-md">Phone Number</label>
                    <input type="text" name="phone" id="phone"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                        placeholder="e.g +1 234 5678" />
                </div>
                <div class="space-y-2 col-span-3">
                    <label for="fullName" class="font-medium text-white text-md">Full Name</label>
                    <input type="text" name="fullName" id="fullName"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                        placeholder="Recipient full name" />
                </div>
                <div class="space-y-2 col-span-3">
                    <label for="transferType" class="font-medium text-white text-md">Transfer Type</label>
                    <select name="transferType" id="transferType"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full">
                        <option value="international">International Transfer</option>
                    </select>
                </div>
                <div class="space-y-2 col-span-3">
                    <label for="iban" class="font-medium text-white text-md">IBAN</label>
                    <input type="text" name="iban" id="iban"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                        placeholder="IBAN" />
                    <div class="flex items-center justify-start text-gray-400 text-xs font-medium">
                        <span>You will have to provide the IBAN for European countries, or the ABA for the United
                            States.
                        </span>
                    </div>
                </div>
                <div class="col-span-3 grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div class="space-y-2">
                        <label for="switft" class="font-medium text-white text-md">Switft Code</label>
                        <input type="text" name="switft" id="switft"
                            class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                            placeholder="Swift Code" />
                    </div>
                    <div class="space-y-2">
                        <label for="accountNumber" class="font-medium text-white text-md">Account Number</label>
                        <input type="text" name="accountNumber" id="accountNumber"
                            class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-md w-full"
                            placeholder="Account Number" />
                    </div>
                </div>

                <div class="col-span-3">
                    <button type="submit"
                        class="w-full p-3 rounded-md bg-blue-700 hover:bg-blue-800 duration-300 text-white text-xm font-semibold">Continue</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/user/transfer/wire/history.html
{% extends '../../_base.html' %}
{% load static %}

{% block title %}
Wire Transfer History
{% endblock %}

{% block content %}
<div class="space-y-10">
    {% include './top-banner.html' %}

    <div class="flex flex-col">
        {% include './tab-menu.html' %}

        <div class="p-8 border border-gray-800 space-y-5 bg-[#141C26] shadow-mg shadow-black">
            <div class="flex items-center justify-between">
                <input type="search" name="search" id="search"
                    class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-sm md:w-1/4 w-full text-sm"
                    placeholder="Type in to Search" />

                <div class="flex space-x-2 items-center">
                    <span class="text-gray-400 text-md">Show</span>

                    <select name="show" id="show"
                        class="px-5 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-sm w-full">
                        <option value="10" class="bg-background_primary">10</option>
                        <option class="bg-background_primary"" value=" 25">25</option>
                        <option class="bg-background_primary"" value=" 50">50</option>
                        <option class="bg-background_primary"" value=" 100">100</option>
                    </select>
                </div>
            </div>

            <div class="border border-gray-800 bg-[#141C26] shadow-mg shadow-black">
                <div class="grid grid-cols-2 md:grid-cols-5 border-b border-gray-800">
                    <div class="px-3 py-2 flex items-center justify-between cursor-pointer">
                        <span class="font-semibold text-gray-400 text-sm">Recipient</span>
                        <i class="ti ti-adjustments text-gray-400"></i>
                    </div>
                    <div class="px-3 py-2 flex items-center justify-between cursor-pointer">
                        <span class="font-semibold text-gray-400 text-sm">Ref Number</span>
                        <i class="ti ti-adjustments text-gray-400"></i>
                    </div>
                    <div class="px-3 py-2 flex items-center justify-between cursor-pointer">
                        <span class="font-semibold text-gray-400 text-sm">Datw</span>
                        <i class="ti ti-adjustments text-gray-400"></i>
                    </div>
                    <div class="px-3 py-2 flex items-center justify-between cursor-pointer">
                        <span class="font-semibold text-gray-400 text-sm">Amount</span>
                        <i class="ti ti-adjustments text-gray-400"></i>
                    </div>
                    <div class="px-3 py-2 flex items-center justify-between cursor-pointer">
                        <span class="font-semibold text-gray-400 text-sm">Description</span>
                        <i class="ti ti-adjustments text-gray-400"></i>
                    </div>
                </div>

                <div class="grid grid-cols-2 md:grid-cols-5">
                    <div class="col-span-5 p-2">
                        <h3 class="text-gray-400 text-center">No data available in table</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/dashboard/user/transfer/wire/tab-menu.html
<div class="p-5 rounded-sm bg-[#3140FC] text-[#98A5E0] flex items-center space-x-5 border-b border-black">
    <div class="flex space-x-2 py-2 items-center border-b-4 border-[#1167FE]">
        <i class="ti ti-wallet text-lg"></i>
        <a href="{% url 'user:wire_transfer' %}" class="text-md text-[#98A5E0] font-semibold">Send Money</a>
    </div>
    <div class="flex space-x-2 py-2 items-center">
        <i class="ti ti-wallet text-lg"></i>
        <a href="{% url 'user:add_a_wire_transfer_recipient' %}" class="text-md text-[#98A5E0] font-semibold">Add a
            Recipient</a>
    </div>
    <div class="flex space-x-2 py-2 items-center">
        <i class="ti ti-wallet text-lg"></i>
        <a href="{% url 'user:wire_transfer_history' %}" class="text-md text-[#98A5E0] font-semibold">History</a>
    </div>
</div>

templates/dashboard/user/transfer/wire/top-banner.html
<div class="p-3 border border-gray-700 text-white rounded-xs">
    <div class="flex flex-col md:flex-row space-x-4 items-center justify-between">
        <div class="space-y-1 w-[70%]">
            <h2 class="text-2xl font-normal">Cross-border transfer</h2>
            <p class="text-gray-500 text-sm">Cross-border transfer is fast and safe way to send money across
                different countries. The funds are deposited into the recipient's bank account associated with the
                IBAN or Swift Code you have added.</p>
        </div>

        <div class="flex items-center justify-end space-x-3 w-[30%]">
            <a href="{% url 'user:interbank_transfer' %}"
                class="px-6 py-2 rounded-sm bg-gray-700 text-gray-400 hover:bg-gray-600 duration-300 font-semibold">
                Local Transfer
                <i class="ti ti-wallet"></i>
            </a>
            <a href=""
                class="px-3 py-2 rounded-sm border border-gray-500 text-white hover:bg-gray-600 duration-300 font-semibold">
                <i class="ti ti-settings"></i>
            </a>
        </div>
    </div>
</div>

templates/dashboard/user/transfer/wire/wire.html
{% extends '../../_base.html' %}
{% load static %}

{% block title %}
Wire Transfer
{% endblock %}

{% block content %}
<div class="space-y-10">
    {% include './top-banner.html' %}

    <div class="flex flex-col">
        {% include './tab-menu.html' %}

        <div class="p-8 border border-gray-800 space-y-5 bg-[#141C26] shadow-mg shadow-black">
            <form method="post" class="space-y-7">
                {% csrf_token %}
                <div class="grid grid-cos-1 md:grid-cols-2 gap-5">
                    <select name="recipient" id="recipient"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-sm">
                        <option value="none">Select a Recipient to be added</option>
                    </select>

                    <input type="date" name="delivery_date" id="delivery_date"
                        class="px-3 py-2 border border-gray-500 bg-transparent text-white outline-none rounded-sm">
                </div>

                <div class="space-y-2 w-full ">
                    <h3 class="font-semibold text-white">Amount</h3>

                    <div class="space-y-1">
                        <div class="flex items-center justify-between text-gray-400 text-xs font-medium">
                            <span>Daily Transfer Limit:</span>
                            <span>USD 0.00 OF USD 5,000.00</span>
                        </div>
                        <input type="text"
                            class="py-4 px-5 border border-gray-700 rounded-sm bg-transparent w-full text-gray-200  outline-none"
                            placeholder="Recipient Account Number" name="amount" id="amount">
                        <div class="flex items-center justify-end text-gray-400 text-xs font-medium">
                            <span>*Cross-border transfer fee will be deducted</span>
                        </div>
                    </div>
                </div>

                <div class="space-y-2 w-full ">
                    <h3 class="font-semibold text-white">Description (Reason)</h3>

                    <div class="space-y-1">
                        <input type="text"
                            class="py-4 px-5 border border-gray-700 rounded-sm bg-transparent w-full text-gray-200  outline-none"
                            placeholder="Recipient Account Number" name="description" id="description">
                    </div>
                </div>

                <button type="submit"
                    class="w-full p-3 rounded-md bg-blue-700 hover:bg-blue-800 duration-300 text-white text-xm font-semibold">Continue
                    to
                    next step</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}